name: Bug Report
description: Report a bug to help us improve
title: '[BUG] '
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing bug report for this?
      description: Please [search Littora issues](https://github.com/thisfilipe/littora/issues?q=is%3Aissue) to see if someone has already reported this bug.
      options:
        - label: I have searched the existing issues before opening this bug report.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: Littora client
      options:
        - Samsung Tizen TV
        - Web
        - Desktop
        - Other
    validations:
      required: true

  - type: input
    id: littora-revision
    attributes:
      label: Littora revision
      description: Add the release version or branch and commit when available.
      placeholder: e.g. develop@abc1234
    validations:
      required: true

  - type: input
    id: jellyfin-version
    attributes:
      label: Jellyfin Version
      placeholder: e.g. 10.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux
        - Tizen (Samsung)
        - WebOS (LG)
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (Web client only)
      placeholder: e.g. Chrome 114
    validations:
      required: false

  - type: dropdown
    id: docker
    attributes:
      label: Running the web client using Docker?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the problem here.
    validations:
      required: false
